// mit NodeJS SQLite zu JSON
// Refactor Schachtelkürzel zu Schachtel
//
// const sqlite3 = require('sqlite3').verbose();
// // const db = new sqlite3.Database('../data/database/Postkarten.sqlite');
//
// let db = new sqlite3.Database('../data/Postkarten.db', (err) => {
//     if (err) {
//         console.error(err.message);
//     }
//     console.log('Connected to Postkarten.');
// });
//
// const sql = "SELECT * FROM 'Abfrage Haupttabelle';";
//
// function get_view(){
//     return new Promise((resolve) => {
//         db.all(sql,[],(err,rows)=>{
//             if(err){
//                 return console.error(err.message);
//             }
//
//             resolve(rows);
//         });
//     });
// }
//
// async function get_entries() {
//     const entries = await get_view();
//     console.log(entries)
// }
//
// get_entries()

const boote = [
    {
        Postkarte: 1,
        Schiff: 'Monarch',
        Klasse: 'Monarch',
        Typ: 'Linienschiff',
        Marine: 'k. u. k. Kriegsmarine',
        Datierung: null,
        Beschreibung: 'SMS Monarch, Steuerboard',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 2,
        Schiff: 'Valorous',
        Klasse: 'V-Klasse',
        Typ: 'DD',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Valorous (ehem. Montrose), Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'W. E. Mack, London, N. W. 3. Sepia "Satin" Series',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 3,
        Schiff: 'Hood',
        Klasse: 'Admiral',
        Typ: 'CB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Hood, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 4,
        Schiff: 'Indomitable',
        Klasse: 'Illustrious',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: 1953,
        Beschreibung: 'Illustration der HMS Indomitable während der\r\n' +
            ' Coronation Fleet Review von Elizabeth II, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Valentine & Sons LTD., Dundee and London',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 5,
        Schiff: 'Nelson',
        Klasse: 'Nelson',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'Bug der HMS Nelson mit feuernde Geschützen A und B',
        Fotograph: null,
        Verlagsbezeichnung: "Raphale Tuck & Sons' Photogravure Postcard No. 2183",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 6,
        Schiff: 'Bellerophon',
        Klasse: 'Bellerophon',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Bellerophon im Hafen, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'The Spithea Series',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 7,
        Schiff: 'Ramilles',
        Klasse: 'Revenge',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Ramilles mit Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: "Valentine's Postcard",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 8,
        Schiff: 'Hood',
        Klasse: 'Admiral',
        Typ: 'CB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Hood mit Crew, Geschütze A,B, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 9,
        Schiff: 'Warspite',
        Klasse: 'Queen Elizabeth',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Warspite mit Crew, Backbord, Nach Refit (1934-1937)',
        Fotograph: null,
        Verlagsbezeichnung: 'W. E. Mack, London, N. W. 3. Sepia "Satin" Series',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 10,
        Schiff: 'Warspite',
        Klasse: 'Queen Elizabeth',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Warspite mit Crew, Backbord, Pre-Refit (<1934)',
        Fotograph: null,
        Verlagsbezeichnung: 'W. E. Mack, London, N.W,3,',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 11,
        Schiff: 'Majestic',
        Klasse: 'Majestic',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1908,
        Beschreibung: 'HMS Majestic, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'The Palatine Pictorial Company LTD., Manchester',
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 12,
        Schiff: 'King Edward VII',
        Klasse: 'King-Edward-VII',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1907,
        Beschreibung: 'HMS King Edward VII mit Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'The Nelson Series',
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 14,
        Schiff: 'King George V',
        Klasse: 'King-George-V (1940)',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'Illustration der HMS King George V, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Copyright. Printed & Published By J. Salmon LTD., Sevenoaks',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 15,
        Schiff: 'Saratoga',
        Klasse: 'Lexington',
        Typ: 'CV',
        Marine: 'United States Navy',
        Datierung: null,
        Beschreibung: 'USS Saratoga, Luftbild des Flugzeugträgers im Hafen (Pearl Habor?), Backbord, Schlachtschiffe im Hintergrund (Nevada-Klasse, Oklahoma und Nevada?)',
        Fotograph: null,
        Verlagsbezeichnung: 'Copyright and Published by REAL Photographs Coopers Buildings, Church St. Liverpool',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 16,
        Schiff: 'Nelson',
        Klasse: 'Nelson',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Nelson mit Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Stephen Cribb, Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 17,
        Schiff: 'Nelson',
        Klasse: 'Nelson',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Nelson mit Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 18,
        Schiff: 'Nelson',
        Klasse: 'Nelson',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Nelson mit Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Stephen Cribb, Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 19,
        Schiff: 'Nelson',
        Klasse: 'Nelson',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Nelson mit Crew',
        Fotograph: null,
        Verlagsbezeichnung: "Valentine's Postcard",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 21,
        Schiff: 'Dominion',
        Klasse: 'King-Edward-VII',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'Illustration der HMS Dominion, Steuerbord, Dienstzeit 1905-1921',
        Fotograph: null,
        Verlagsbezeichnung: 'Gale & Polden, LTD.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 22,
        Schiff: 'Sheffield',
        Klasse: 'Town',
        Typ: 'CL',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Sheffield, Steuerbord, Southhampton Unterklasse der Townklasse',
        Fotograph: null,
        Verlagsbezeichnung: "Valentine's Postcard",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 23,
        Schiff: 'Leander',
        Klasse: 'Leander',
        Typ: 'CL',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Leander mit Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: "Valentine's Postcard",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 24,
        Schiff: 'Littorio',
        Klasse: 'Littorio',
        Typ: 'BB',
        Marine: 'Regia Marina',
        Datierung: 1940,
        Beschreibung: 'RM Littorio, Illustration, Backbord, 18.Oktober 1940',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 25,
        Schiff: 'Nürnberg',
        Klasse: 'Leipzig',
        Typ: 'CL',
        Marine: 'Kriegsmarine',
        Datierung: 1937,
        Beschreibung: 'KM Nürnberg, Backbord, 1935-1937',
        Fotograph: null,
        Verlagsbezeichnung: 'M. Dieterle & Sohn, Kiel. Reihe Heimat',
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 26,
        Schiff: 'Prinz Eugen',
        Klasse: 'Admiral-Hipper',
        Typ: 'CB',
        Marine: 'Kriegsmarine',
        Datierung: null,
        Beschreibung: 'KM Prinz Eugen vor Anker, Backbord, 1938-1945',
        Fotograph: null,
        Verlagsbezeichnung: 'EAS',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 27,
        Schiff: 'Zerstörer 1934 Leberecht Maas Z1',
        Klasse: 'Zerstörer 1934',
        Typ: 'DD',
        Marine: 'Kriegsmarine',
        Datierung: null,
        Beschreibung: 'KM Zerstörer 1934, Steuerbord, Leberecht Maas, Z1',
        Fotograph: null,
        Verlagsbezeichnung: 'Ross=Verlag, Berlin SW 68. Freigegeben O.K.W. Übungsaufnahme',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 28,
        Schiff: 'Panzerschiff Admiral Scheer',
        Klasse: 'Deutschland-Klasse (1931)',
        Typ: 'CB',
        Marine: 'Kriegsmarine',
        Datierung: 1939,
        Beschreibung: 'KM Panzerschiff Admiral Scheer, Steuerbord, Dienstzeit 1933-1945, Stempel Wilhelmshaven 1. April 1939',
        Fotograph: null,
        Verlagsbezeichnung: 'M. Dieterle & Sohn, Kiel. Reihe Heimat Nr. 5218',
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 29,
        Schiff: 'Panzerschiff Deutschland',
        Klasse: 'Deutschland-Klasse (1931)',
        Typ: 'CB',
        Marine: 'Kriegsmarine',
        Datierung: 1941,
        Beschreibung: 'KM Panzerschiff Deutschland, Backbord, Dienstzeit 1933-1945',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 30,
        Schiff: 'Gneisenau',
        Klasse: 'Scharnhorst',
        Typ: 'BB',
        Marine: 'Kriegsmarine',
        Datierung: 1941,
        Beschreibung: 'KM Schlachtschiff Gneisenau, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Trinks & Co., Leipzig Nr. 2003',
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 31,
        Schiff: 'Ark Royal',
        Klasse: 'Ark-Royal',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Ark-Royal, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Real Photographs Coopers Buildings. Church St., Liverppol',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 32,
        Schiff: 'Renown',
        Klasse: 'Renown',
        Typ: 'CB',
        Marine: 'Royal Navy',
        Datierung: 1931,
        Beschreibung: 'HMS Renown, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 33,
        Schiff: 'Repulse',
        Klasse: 'Renown',
        Typ: 'CB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Repulse, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 34,
        Schiff: 'Repulse',
        Klasse: 'Renown',
        Typ: 'CB',
        Marine: 'Royal Navy',
        Datierung: 1925,
        Beschreibung: 'HMS Repulse, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 35,
        Schiff: 'Renown',
        Klasse: 'Renown',
        Typ: 'CB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Renown, Steuerbord, nach 3. Refit(?)',
        Fotograph: null,
        Verlagsbezeichnung: 'Imperial War Museum, National Maritime Museum Card No. 221',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 36,
        Schiff: 'Warspite',
        Klasse: 'Queen Elizabeth',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Warspite, Steuerbord, Prerefit',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 37,
        Schiff: 'Hood',
        Klasse: 'Admiral',
        Typ: 'CB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Hood, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'M. & Co.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 38,
        Schiff: 'Illustrious',
        Klasse: 'Illustrious',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Illustrious mit Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Tom Molland Limited, Incorporating Roy, Smith, A.I.B.P. & Arcadian Photos (Plymouth) 102 Cornwall Street, Plymouth',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 39,
        Schiff: 'Formidable',
        Klasse: 'Illustrious',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Formidable mit Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Real Photographs Co., Ltd., Victoria House, Southport, Lincs',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 40,
        Schiff: 'Victorious',
        Klasse: 'Illustrious',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Victorious mit Crew, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers Albert Road Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 41,
        Schiff: 'Illustrious',
        Klasse: 'Illustrious',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: 1951,
        Beschreibung: 'HMS Illustrious mit Crew, Steuerbord, Juni 1951',
        Fotograph: null,
        Verlagsbezeichnung: 'P. A. … Leander, Crome…',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 42,
        Schiff: 'Unicorn',
        Klasse: 'Unicorn',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: 1954,
        Beschreibung: 'HMS Unicorn mit Crew, Steuerbord, 11 Mai 1954, Malta(?)',
        Fotograph: null,
        Verlagsbezeichnung: "Anthony & Joseph Pavia, 6. St. John's Street, Valletta, Malta.",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 43,
        Schiff: 'Dainty',
        Klasse: 'Daring',
        Typ: 'DD',
        Marine: 'Royal Navy',
        Datierung: 1964,
        Beschreibung: 'HMS Dainty, Backbord, August 1964',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers Albert Road Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 44,
        Schiff: 'Queen Elizabeth',
        Klasse: 'Queen Elizabeth',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1937,
        Beschreibung: 'HMS Queen Elizabeth mit Crew, Steuerbord, Mai 1937',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers Albert Road Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 45,
        Schiff: 'Takao Klasse',
        Klasse: 'Takao',
        Typ: 'CA',
        Marine: 'Imperial Japanese Navy',
        Datierung: null,
        Beschreibung: 'IJN Takao-Klasse, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 46,
        Schiff: 'Nagato, Mutsu',
        Klasse: 'Nagato',
        Typ: 'BB',
        Marine: 'Imperial Japanese Navy',
        Datierung: null,
        Beschreibung: 'IJN Nagato-Klasse, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 47,
        Schiff: 'Kongo',
        Klasse: 'Kongo',
        Typ: 'CB',
        Marine: 'Imperial Japanese Navy',
        Datierung: null,
        Beschreibung: 'IJN Kongo, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 48,
        Schiff: 'Akagi',
        Klasse: 'Amagi',
        Typ: 'CV',
        Marine: 'Imperial Japanese Navy',
        Datierung: null,
        Beschreibung: 'IJN Akagi, umgebauter Schlachtkreuzer, Backbord, Pre-Refit, zwischen 1927-1935 (Flugdeck)',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 49,
        Schiff: 'Mogami Klasse',
        Klasse: 'Mogami',
        Typ: 'CA',
        Marine: 'Imperial Japanese Navy',
        Datierung: null,
        Beschreibung: 'IJN Mogami-Klasse, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 50,
        Schiff: 'Yamashiro',
        Klasse: 'Fuso',
        Typ: 'BB',
        Marine: 'Imperial Japanese Navy',
        Datierung: null,
        Beschreibung: 'IJN Yamashiro, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 51,
        Schiff: 'Pennsylvania',
        Klasse: 'Pennsylvania',
        Typ: 'BB',
        Marine: 'United States Navy',
        Datierung: null,
        Beschreibung: 'USS Pennsylvania, Illustration, Steuerbord, Ausstatung von 1916',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 52,
        Schiff: 'Warspite',
        Klasse: 'Queen Elizabeth',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Warspite, Steuerbord, Post Refit, mit Crew',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 53,
        Schiff: 'Zeitungsartikel Warspite',
        Klasse: 'Queen Elizabeth',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1940,
        Beschreibung: 'HMS Warspite, Zeitungsartikel über Schiff zu Narvik',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 54,
        Schiff: 'Furutaka Klasse',
        Klasse: 'Furutaka',
        Typ: 'CA',
        Marine: 'Imperial Japanese Navy',
        Datierung: null,
        Beschreibung: 'IJN Furutaka Klasse, Furutaka oder Kako, Steuerbord, Doppeldecker im Hintergrund',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 55,
        Schiff: 'Ise',
        Klasse: 'Ise',
        Typ: 'BB',
        Marine: 'Imperial Japanese Navy',
        Datierung: null,
        Beschreibung: 'IJN Ise, Illustration, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 56,
        Schiff: 'Enterprise',
        Klasse: 'Yorktown',
        Typ: 'CV',
        Marine: 'United States Navy',
        Datierung: null,
        Beschreibung: 'USS Enterprise, CV-6, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'The L. L. Cook Co., Milwaukee',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 57,
        Schiff: 'Le Malin',
        Klasse: 'Le Fantasque',
        Typ: 'DD',
        Marine: 'Marine nationale',
        Datierung: null,
        Beschreibung: 'MN Le Malin, im Hafen, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Edition < La Cigale >',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 58,
        Schiff: 'Le Terrible',
        Klasse: 'Le Fantasque',
        Typ: 'DD',
        Marine: 'Marine nationale',
        Datierung: null,
        Beschreibung: 'MN Le Terrible, im Hafen, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 59,
        Schiff: 'La Galissonere',
        Klasse: 'La Galissonnière',
        Typ: 'CL',
        Marine: 'Marine nationale',
        Datierung: null,
        Beschreibung: 'MN La Galissonere, Steuerbord',
        Fotograph: 'Adia',
        Verlagsbezeichnung: 'Photocromie A.D.I.A. - (St. Roch) Nice (A.-M.)',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 60,
        Schiff: 'Marseillaise',
        Klasse: 'La Galissonnière',
        Typ: 'CL',
        Marine: 'Marine nationale',
        Datierung: null,
        Beschreibung: 'MN Marseillaise, im Hafen, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Edition < La Cigale >',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 61,
        Schiff: 'Siroco',
        Klasse: 'Bourrasque',
        Typ: 'DD',
        Marine: 'Marine nationale',
        Datierung: null,
        Beschreibung: 'MN Siroco, T62, im Hafen, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Edition < La Cigale >',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 62,
        Schiff: 'Jeanne-d´Arc',
        Klasse: "Jeanne d'Arc",
        Typ: 'CL',
        Marine: 'Marine nationale',
        Datierung: null,
        Beschreibung: 'MN Jeanne-d´Arc, im Hafen, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Edition < La Cigale >',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 63,
        Schiff: 'Bretagne',
        Klasse: 'Bretagne',
        Typ: 'BB',
        Marine: 'Marine nationale',
        Datierung: null,
        Beschreibung: 'MN Bretagne, im Hafen, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Edition < La Cigale >',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 64,
        Schiff: 'Cossack',
        Klasse: 'Tribal',
        Typ: 'DD',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Cossack, L03, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Valentine & Sons LTD., Dundee and London',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 65,
        Schiff: 'Howe',
        Klasse: 'King-George-V (1940)',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Howe, Illustration, Steuerbord',
        Fotograph: 'AFD. Bannister',
        Verlagsbezeichnung: 'Copyright. Printed & Published by J. Salmon LTD., Sevenoaks',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 66,
        Schiff: 'Nelson',
        Klasse: 'Nelson',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Nelson, Illustration, Steuerbord',
        Fotograph: 'Bernard W. Church',
        Verlagsbezeichnung: 'Copyright. Printed & Published by J. Salmon LTD., Sevenoaks',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 67,
        Schiff: 'Renown',
        Klasse: 'Renown',
        Typ: 'CB',
        Marine: 'Royal Navy',
        Datierung: 1932,
        Beschreibung: 'HMS Renown, Illustration, Backbord',
        Fotograph: 'AFD. Bannister 1932',
        Verlagsbezeichnung: 'Copyright. Printed & Published by J. Salmon LTD., Sevenoaks',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 68,
        Schiff: 'Formidable',
        Klasse: 'Illustrious',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Formidable, Illustration, Steuerbord',
        Fotograph: 'AFD. Bannister',
        Verlagsbezeichnung: 'Copyright. Printed & Published by J. Salmon LTD., Sevenoaks',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 69,
        Schiff: 'Barham',
        Klasse: 'Queen Elizabeth',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1937,
        Beschreibung: 'HMS Barham, Illustration, Backbord',
        Fotograph: 'AFD. Bannister 1937',
        Verlagsbezeichnung: 'Copyright. Printed & Published by J. Salmon LTD., Sevenoaks',
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 70,
        Schiff: 'Lightning',
        Klasse: 'L- M Class',
        Typ: 'DD',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Lightning, G55, Illustration, Backbord',
        Fotograph: 'AFD. Bannister',
        Verlagsbezeichnung: 'Copyright. Printed & Published by J. Salmon LTD., Sevenoaks',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 71,
        Schiff: 'Rodney',
        Klasse: 'Nelson',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1937,
        Beschreibung: 'HMS Rodney, Illustration, Steuerbord',
        Fotograph: 'AFD. Bannister 1937',
        Verlagsbezeichnung: 'Copyright. Printed & Published by J. Salmon LTD., Sevenoaks',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 72,
        Schiff: 'Ark Royal',
        Klasse: 'Ark-Royal',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Ark Royal, Flugdeck, Bug, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Valentine & Sons LTD., Dundee and London',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 73,
        Schiff: 'Queen Elizabeth',
        Klasse: 'Queen Elizabeth',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Queen Elizabeth, Post-Refit, Luftbild, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Valentine & Sons LTD., Dundee and London',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 74,
        Schiff: 'Furious',
        Klasse: 'Courageous',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Furious mit einem Geschwader Torpedobomer "Blackburn B-5 Faffin", Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: "Valentine's Postcard",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 75,
        Schiff: 'Hermes',
        Klasse: 'Hermes',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Hermes, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 76,
        Schiff: 'Duke of York',
        Klasse: 'King-George-V (1940)',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1944,
        Beschreibung: 'HMS Duke of York, Illustration, Steuerbord',
        Fotograph: 'AFD. Bannister',
        Verlagsbezeichnung: 'Copyright. Printed & Published by J. Salmon LTD., Sevenoaks',
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 77,
        Schiff: 'Mogador',
        Klasse: 'Mogador',
        Typ: 'DD',
        Marine: 'Marine nationale',
        Datierung: null,
        Beschreibung: 'MN Mogador, X62, Illustration, Steuerbord',
        Fotograph: 'L. Haffner',
        Verlagsbezeichnung: 'Collection de la ligue Maritime et Coloniale, E AEC Paris',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 78,
        Schiff: 'Marseillaise',
        Klasse: 'La Galissonnière',
        Typ: 'CL',
        Marine: 'Marine nationale',
        Datierung: null,
        Beschreibung: 'MN Marseillaise, Illustration, Backbord',
        Fotograph: 'L. Haffner',
        Verlagsbezeichnung: 'Collection de la ligue Maritime et Coloniale, E AEC Paris',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 79,
        Schiff: 'Tourville',
        Klasse: 'Tourville',
        Typ: 'CA',
        Marine: 'Marine nationale',
        Datierung: null,
        Beschreibung: 'MN Tourville, Illustration, Steuerbord',
        Fotograph: 'Max Cremnitz / L. Haffner',
        Verlagsbezeichnung: 'Ligue Martime Et Coloniale',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 80,
        Schiff: 'Algérie',
        Klasse: 'Algérie',
        Typ: 'CA',
        Marine: 'Marine nationale',
        Datierung: null,
        Beschreibung: 'MN Algérie vor Anker, Reinigung, Illustration, Bug, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Édition Léon Barra - Toulon',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 81,
        Schiff: 'Algérie',
        Klasse: 'Algérie',
        Typ: 'CA',
        Marine: 'Marine nationale',
        Datierung: null,
        Beschreibung: 'MN Algérie vor Anker mit Crew, Illustration, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Cliché Emery - Édition Bouvet Sourd - Toulon',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 82,
        Schiff: 'Courbet',
        Klasse: 'Courbet',
        Typ: 'BB',
        Marine: 'Marine nationale',
        Datierung: null,
        Beschreibung: 'MN Courbet an Küste, Illustration, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Cliché Emery - Édition Bouvet Sourd - Toulon',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 83,
        Schiff: 'Zara',
        Klasse: 'Zara',
        Typ: 'CA',
        Marine: 'Regia Marina',
        Datierung: null,
        Beschreibung: 'RM Zara mit Geschützen Cäsar und Dora, ausgerichtet nach Backbord, Richtung Bug fotografiert - hintere Mast im Bild',
        Fotograph: null,
        Verlagsbezeichnung: 'S. A. Istituto Editoriale Nazionale - Milano',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 84,
        Schiff: 'Richelieu',
        Klasse: 'Richelieu',
        Typ: 'BB',
        Marine: 'Marine nationale',
        Datierung: 1970,
        Beschreibung: 'MN Richeleu im Hafen von Brest, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Les Belles Editions de Bretagne - Quimper - Photo Y. Caoudal',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 85,
        Schiff: 'New Jersey',
        Klasse: 'Iowa',
        Typ: 'BB',
        Marine: 'United States Navy',
        Datierung: 1947,
        Beschreibung: 'USS New Jersey, BB-62, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan, Photographers Albert Road Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 86,
        Schiff: 'Missouri',
        Klasse: 'Iowa',
        Typ: 'BB',
        Marine: 'United States Navy',
        Datierung: 1949,
        Beschreibung: 'USS Missouri, BB-63, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan, Photographers Albert Road Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 87,
        Schiff: 'Graf Zeppelin',
        Klasse: 'Graf Zeppelin',
        Typ: 'CV',
        Marine: 'Kriegsmarine',
        Datierung: 1941,
        Beschreibung: 'KM Graf Zepellin in Kiel, im Bau, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Foto Drüppel, W´-Haven, Rheinstr, 50, RM1451',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 88,
        Schiff: 'Repulse',
        Klasse: 'Renown',
        Typ: 'CB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Repulse, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Abrahams. Devonport, Tom Molland Ltd, 102 Cornwall Street Plymouth. Ref. No 2543',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 89,
        Schiff: 'Vanguard',
        Klasse: 'Vanguard',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1956,
        Beschreibung: 'HMS Vanguard, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Tom Molland Ltd, 102 Cornwall Street Plymouth. Ref. No 2543',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 90,
        Schiff: 'Duke of York',
        Klasse: 'King-George-V (1940)',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Duke of York, Photo passed by Censor, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Tom Molland Ltd, 102 Cornwall Street Plymouth. Ref. No. 2639',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 91,
        Schiff: 'USS Kearsarge',
        Klasse: 'Kearsarge',
        Typ: 'BB',
        Marine: 'United States Navy',
        Datierung: 1906,
        Beschreibung: 'USS Kearsarge, BB-6, Illustration, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Illustrated Postal Card of New-York-Leipzig',
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 92,
        Schiff: 'Tirpitz',
        Klasse: 'Bismarck',
        Typ: 'BB',
        Marine: 'Kriegsmarine',
        Datierung: null,
        Beschreibung: 'KM Tirpitz, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'K. Joswig, Hamburg … fach 187',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 93,
        Schiff: 'Tirpitz',
        Klasse: 'Bismarck',
        Typ: 'BB',
        Marine: 'Kriegsmarine',
        Datierung: null,
        Beschreibung: 'KM Tirpitz, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 94,
        Schiff: 'Tirpitz',
        Klasse: 'Bismarck',
        Typ: 'BB',
        Marine: 'Kriegsmarine',
        Datierung: 1939,
        Beschreibung: 'KM Tirpitz Stapellauf am 1. April 1939, Wilhelmshaven',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 95,
        Schiff: 'Tirpitz',
        Klasse: 'Bismarck',
        Typ: 'BB',
        Marine: 'Kriegsmarine',
        Datierung: 1939,
        Beschreibung: 'KM Tirpitz Stapellauf am 1. April 1939, Wilhelmshaven',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 96,
        Schiff: 'Tirpitz',
        Klasse: 'Bismarck',
        Typ: 'BB',
        Marine: 'Kriegsmarine',
        Datierung: 1939,
        Beschreibung: 'KM Tirpitz Stapellauf am 1. April 1939, NS-Beflaggung, Zuschaer, Hitlergruß, Wilhelmshaven',
        Fotograph: null,
        Verlagsbezeichnung: 'Photo-Hasse, Wilhelmshaven, Bismarckstr. 91.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 97,
        Schiff: 'Tirpitz',
        Klasse: 'Bismarck',
        Typ: 'BB',
        Marine: 'Kriegsmarine',
        Datierung: null,
        Beschreibung: 'KM Tirpitz, Geschützturm Dora, vor Küste (eventuell Norwegen), deutscher Zerstörer (1934A?) im Hintergrund',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 98,
        Schiff: 'Tirpitz',
        Klasse: 'Bismarck',
        Typ: 'BB',
        Marine: 'Kriegsmarine',
        Datierung: null,
        Beschreibung: 'KM Tirpitz, Flugzeug wird von Schiffskran gehoben, im Hintergrund deutscher Zerstörer (1934A?)',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 99,
        Schiff: 'Tirpitz',
        Klasse: 'Bismarck',
        Typ: 'BB',
        Marine: 'Kriegsmarine',
        Datierung: null,
        Beschreibung: 'KM Tirpitz feuer mit Geschützen Anton und Berta, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 100,
        Schiff: 'Tirpitz',
        Klasse: 'Bismarck',
        Typ: 'BB',
        Marine: 'Kriegsmarine',
        Datierung: null,
        Beschreibung: 'KM Tirpitz, Bug fotografiert von vorraussfahrendem Zerstörer (1934A?)',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 101,
        Schiff: 'Tirpitz',
        Klasse: 'Bismarck',
        Typ: 'BB',
        Marine: 'Kriegsmarine',
        Datierung: null,
        Beschreibung: 'KM Tirpitz im Fættenfjord in Norwegen zwischen 1942 und 1943, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'W3-Bilddienst D-26382 Wilhelmshaven Börsenstraße 29. Bestell-Nr. J0545',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 102,
        Schiff: 'Tirpitz',
        Klasse: 'Bismarck',
        Typ: 'BB',
        Marine: 'Kriegsmarine',
        Datierung: null,
        Beschreibung: 'KM Tirpitz, Seitenansicht mit Geschützen Anton, Berta, Sekundärbatterie, Torpedowerfer, vor Norwegen?, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'W3-Bilddienst D-26382 Wilhelmshaven Börsenstraße 29. Bestell-Nr. J4424',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 103,
        Schiff: 'Tirpitz',
        Klasse: 'Bismarck',
        Typ: 'BB',
        Marine: 'Kriegsmarine',
        Datierung: null,
        Beschreibung: 'KM Tirpitz, im Kaafjord in Norwegen, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'W3-Bilddienst D-26382 Wilhelmshaven Börsenstraße 29. Bestell-Nr. J3057',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 105,
        Schiff: 'Hitler und Offiziere bei Stapellauf der Tirpitz',
        Klasse: 'Bismarck',
        Typ: 'BB',
        Marine: 'Kriegsmarine',
        Datierung: 1939,
        Beschreibung: 'KM Tirpitz, Hitler und Offiziere bei Stappellauf am 1. April 1939, Wappen der Tirpitz am Rumpf, NS Beflaggung, Wilhelmshaven',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 106,
        Schiff: 'Hitler und Offiziere bei Stapellauf der Tirpitz',
        Klasse: 'Bismarck',
        Typ: 'BB',
        Marine: 'Kriegsmarine',
        Datierung: 1939,
        Beschreibung: 'KM Tirpitz, Hitler und Offiziere bei Stappellauf am 1. April 1939,Wilhelmshaven, Hitlergruß',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 107,
        Schiff: 'Valiant',
        Klasse: 'Queen Elizabeth',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Valiant, Post-Refit, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: '"Beward" Wessex Series. Copyright',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 108,
        Schiff: 'Colossus',
        Klasse: 'Colossus (1910)',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Colossus, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: '"Our Ironclads" Series I, Raphael Tuck & Sons "Photogravure" Postcard No.4300',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 109,
        Schiff: 'Asama',
        Klasse: 'Asama',
        Typ: 'CL',
        Marine: 'Imperial Japanese Navy',
        Datierung: null,
        Beschreibung: 'IJN Asama und Takasago, Illustration, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 110,
        Schiff: 'Nelson',
        Klasse: 'Nelson',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Nelson, Illustration, Steuerbord',
        Fotograph: 'Bernard W. Church',
        Verlagsbezeichnung: 'Copyright. Printed & Published by J. Salmon LTD., Sevenoaks.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 111,
        Schiff: 'Courageous',
        Klasse: 'Courageous',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Courageous, Crew, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Gieves Ltd.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 112,
        Schiff: 'Broke',
        Klasse: 'Thornycroft',
        Typ: 'DD',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Broke, mit voller Beflaggung, vor Anker, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'MPL',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 113,
        Schiff: 'Collingwood',
        Klasse: 'St.-Vincent',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Collingwood, Crew, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'C. W Faulkner & Co., Ltd., London, E.C.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 114,
        Schiff: 'Leander',
        Klasse: 'Leander',
        Typ: 'CL',
        Marine: 'Royal Navy',
        Datierung: 1946,
        Beschreibung: 'HMS Leander mit Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan, Strictly Copyright 20 Queen Street Portsea Portsmouth',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 115,
        Schiff: 'Renown',
        Klasse: 'Renown',
        Typ: 'CB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Renown, not passed by Censor, Stempel, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 116,
        Schiff: 'Hawkins',
        Klasse: 'Hawkins',
        Typ: 'CA',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Hawkins, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: "Valentine's Post Card",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 117,
        Schiff: 'Bulkwark',
        Klasse: 'Centaur',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Bulkwark, Bug, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Published in England by Gale & Polden LTD. Wellington Press, Aldershot, London, Portsmouth, Chatham.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 118,
        Schiff: 'Vanoc',
        Klasse: 'V-Klasse',
        Typ: 'DD',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Vanoc, H33, Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: "Valentine's Post Card",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 119,
        Schiff: 'Rodney',
        Klasse: 'Nelson',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1936,
        Beschreibung: 'HMS Rodney, Illustration, Steuerbord',
        Fotograph: 'AFD Bannister',
        Verlagsbezeichnung: 'Copyright. Printed & Published by J. Salmon LTD., Sevenoaks',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 120,
        Schiff: 'Argus',
        Klasse: 'Argus',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: 1939,
        Beschreibung: 'HMS Argus, März 1939, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan, Strictly Copyright 20 Queen Street Portsea Portsmouth',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 121,
        Schiff: 'Warrior',
        Klasse: 'Colossus (1942)',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Warrior, Luftbild, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Published in England by Gale & Polden LTD. Wellington Press, Aldershot, London, Portsmouth, Chatham.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 122,
        Schiff: 'Commonwealth',
        Klasse: 'King-Edward-VII',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Commonwealth, Crew, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 123,
        Schiff: 'Cavalier',
        Klasse: 'C-Class-Cruiser',
        Typ: 'DD',
        Marine: 'Royal Navy',
        Datierung: 1970,
        Beschreibung: 'HMS Cavalier, R73, Februar 1970, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan, Strictly Copyright 20 Queen Street Portsea Portsmouth',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 124,
        Schiff: 'Effingham',
        Klasse: 'Hawkins',
        Typ: 'CA',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Effingham, Beflaggung, Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: "Valentine's Post Card",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 125,
        Schiff: 'Theseus',
        Klasse: 'Colossus (1942)',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Theseus, Crew, vor Malta(?), Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Published in England by Gale & Polden LTD. Wellington Press, Aldershot, London, Portsmouth, Chatham.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 126,
        Schiff: 'Icarus',
        Klasse: 'I-Class',
        Typ: 'DD',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Icarus, D03, Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: "Valentine's Post Card",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 127,
        Schiff: 'Foxhound',
        Klasse: 'F-Class',
        Typ: 'DD',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Foxhound, H69, Crew, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Valentine & Sons LTD., Dundee and London',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 128,
        Schiff: 'Frobisher',
        Klasse: 'Hawkins',
        Typ: 'CA',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Frobisher, Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Valentine & Sons LTD., Dundee and London',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 129,
        Schiff: 'Southampton',
        Klasse: 'Town',
        Typ: 'CL',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Southampton, Beflaggung, Crew, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: "Valentine's Post Card",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 130,
        Schiff: 'Warspite',
        Klasse: 'Queen Elizabeth',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Warspite, Illustration, Backbord',
        Fotograph: 'Bernard W. Church',
        Verlagsbezeichnung: 'Copyright. Printed & Published by J. Salmon LTD., Sevenoaks',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 131,
        Schiff: 'Ajax',
        Klasse: 'Leander',
        Typ: 'CL',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Ajax, Illustration, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Copyright. Printed & Published by J. Salmon LTD., Sevenoaks',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 132,
        Schiff: 'Tartar',
        Klasse: 'Tribal',
        Typ: 'DD',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Tartar, Illustration, Backbord',
        Fotograph: 'Bernard W. Church',
        Verlagsbezeichnung: 'Copyright. Printed & Published by J. Salmon LTD., Sevenoaks',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 133,
        Schiff: 'Newcastle',
        Klasse: 'Town',
        Typ: 'CL',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Newcastle, Southampton Subklasse, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: "Valentine's Post Card",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 134,
        Schiff: 'Nelson',
        Klasse: 'Nelson',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1939,
        Beschreibung: 'HMS Nelson, 1. Oktober 1939, Backbbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Copyright and Published by Real Photographs Co., Coopers Buildings, Church St., Liverpool.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 135,
        Schiff: 'Emerald',
        Klasse: 'E-Class',
        Typ: 'CL',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Emerald, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: "Valentine's Post Card",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 136,
        Schiff: 'Queen Elizabeth',
        Klasse: 'Queen Elizabeth',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Queen Elizabeth, Luftbild, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: "Valentine's Post Card",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 137,
        Schiff: 'Nelson',
        Klasse: 'Nelson',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Nelson, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: "Valentine's Post Card",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 138,
        Schiff: 'Norfolk',
        Klasse: 'County',
        Typ: 'CA',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Norfolk, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Copyright and Published by Real Photographs Co., Coopers Buildings, Church St., Liverpool.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 139,
        Schiff: 'Newcastle',
        Klasse: 'Town',
        Typ: 'CL',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Newcastle, Southampton Subklasse, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Copyright and Published by Real Photographs Co., Coopers Buildings, Church St., Liverpool.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 140,
        Schiff: 'Southampton',
        Klasse: 'Town',
        Typ: 'CL',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Southampton, Southampton Subklasse, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Copyright and Published by Real Photographs Co., Coopers Buildings, Church St., Liverpool.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 141,
        Schiff: 'Shropshire',
        Klasse: 'County',
        Typ: 'CA',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Shropshire/HMAS Shropshire, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Copyright and Published by Real Photographs Co., Coopers Buildings, Church St., Liverpool.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 142,
        Schiff: 'Sirius',
        Klasse: 'Dido',
        Typ: 'CL',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Sirius, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'W. Ralstown LTD. Glasgow',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 143,
        Schiff: 'Bellerophon',
        Klasse: 'Bellerophon',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1907,
        Beschreibung: 'HMS Bellerophon, Stapellauf 27. Juli 1907',
        Fotograph: 'Mora Photo',
        Verlagsbezeichnung: null,
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 144,
        Schiff: 'Aurora',
        Klasse: 'Arethusa',
        Typ: 'CL',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Auroral, Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Abrahams, Plymouth,',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 145,
        Schiff: 'King George V',
        Klasse: 'King-George-V (1940)',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS King-George-V, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Valentine & Sons LTD. Dundee and London',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 146,
        Schiff: 'Eagle',
        Klasse: 'Eagle',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Eagle, Luftbild mit Dippeldecker, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 147,
        Schiff: 'Anson',
        Klasse: 'King-George-V (1940)',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Anson, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Valentine & Sons LTD. Dundee and London',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 148,
        Schiff: 'Rodney',
        Klasse: 'Nelson',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Rodney, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Abrahams, Devonport',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 149,
        Schiff: 'Nelson-Class',
        Klasse: 'Nelson',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1953,
        Beschreibung: 'Schiff der Nelson Klasse im Hafen von Portsmouth, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 150,
        Schiff: 'Nelson-Class',
        Klasse: 'Nelson',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1931,
        Beschreibung: 'Schiff der Nelson Klasse im Hafen von Portsmouth, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 151,
        Schiff: 'Anson',
        Klasse: 'King-George-V (1940)',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1955,
        Beschreibung: 'HMS Anson, Illustration, Steuerbord',
        Fotograph: 'C. King',
        Verlagsbezeichnung: `Valentine's "Royal Navy" Series. Copyright. Published by Valentine & Sons LTD., Dundee and London`,
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 152,
        Schiff: 'Gneisenau',
        Klasse: 'Scharnhorst',
        Typ: 'BB',
        Marine: 'Kriegsmarine',
        Datierung: null,
        Beschreibung: 'KM Gneisenau, Crew, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 153,
        Schiff: 'London',
        Klasse: 'County',
        Typ: 'CA',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS London, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 154,
        Schiff: 'Hindustan',
        Klasse: 'King-Edward-VII',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Hindustan, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Boots Cash Chemists, "Real Photgraph" Series.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 155,
        Schiff: 'Formidable',
        Klasse: 'Illustrious',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: 1942,
        Beschreibung: 'HMS Formidable, August 1942, Luftbild, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 156,
        Schiff: 'Ark Royal',
        Klasse: 'Ark-Royal',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Ark Royal, Illustration, Steuerbord',
        Fotograph: 'Bernard W. Church',
        Verlagsbezeichnung: 'J. Salmon LTD., Sevenoaks',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 157,
        Schiff: 'Furious',
        Klasse: 'Furious',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Furious, Bug, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Sellicks. Plymouth / The Bookstall, H.M.S "Furious"',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 158,
        Schiff: 'Daring',
        Klasse: 'Daring',
        Typ: 'DD',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Daring, Crew, Luftbild, Backbord',
        Fotograph: 'H.M.S. Ganges',
        Verlagsbezeichnung: 'Printed by R. A. Fisk.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 159,
        Schiff: 'Yamato',
        Klasse: 'Yamato',
        Typ: 'BB',
        Marine: 'Imperial Japanese Navy',
        Datierung: null,
        Beschreibung: 'IJN Yamato, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Copyright anbd Published by: Real Photographs Co. LTD. 13 Victoria Road, Ramsgate, Kent.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 160,
        Schiff: 'Z18 Hans Lüdemann',
        Klasse: 'Zerstörer 1936',
        Typ: 'DD',
        Marine: 'Kriegsmarine',
        Datierung: null,
        Beschreibung: 'KM Z18 Hans Lüdemann (53), Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Julius Simonsen Oldenburg in Holstein, Freig. V. O. K. W. 17. 3. 43.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 161,
        Schiff: 'Katori',
        Klasse: 'Katori',
        Typ: 'BB',
        Marine: 'Imperial Japanese Navy',
        Datierung: null,
        Beschreibung: 'IJN Katori, Pre-Dreadnought',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '24x30',
        'Schachtel': 'G1'
    },
    {
        Postkarte: 162,
        Schiff: 'Sussex',
        Klasse: 'County',
        Typ: 'CA',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Sussex, London Class (Subklasse von County), Illustration, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Copyright. Printed & Published by J. Salmon LTD., Sevenoaks',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 163,
        Schiff: 'Hermes',
        Klasse: 'Hermes',
        Typ: 'CV',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Hermes, Illustration, Steuerbord',
        Fotograph: 'Leslie Carr',
        Verlagsbezeichnung: 'Copyright. Printed & Published by J. Salmon LTD., Sevenoaks',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 164,
        Schiff: 'Majestic',
        Klasse: 'Majestic',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1982,
        Beschreibung: 'HMS Majestic, Illustration, 16. Mai 1982 Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'GD&DL',
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 165,
        Schiff: 'Saratoga',
        Klasse: 'Lexington',
        Typ: 'CV',
        Marine: 'United States Navy',
        Datierung: null,
        Beschreibung: 'USS Saratoga vor San Francisco mit Schlachtschiffen, Ilustration, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Stanley A. Piltz',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 166,
        Schiff: 'Ranger',
        Klasse: 'Hawthorn Leslie Twenty-seven-knotter',
        Typ: 'DD',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Ranger, Torpedo Destroyer, Illustration, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 167,
        Schiff: 'Nelson',
        Klasse: 'Nelson',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1930,
        Beschreibung: 'HMS Nelson, Illustration, 29. November 1930, Backbord',
        Fotograph: 'Leslie Carr',
        Verlagsbezeichnung: 'Copyright. Printed & Published by J. Salmon, Sevenoaks England',
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 168,
        Schiff: 'Somali',
        Klasse: 'Tribal',
        Typ: 'DD',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Somali, Illustration, Backbord',
        Fotograph: 'Bernard W. Church',
        Verlagsbezeichnung: 'J. Salmon LTD., Sevenoaks',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 169,
        Schiff: 'Andrea Doria',
        Klasse: 'Caio-Duilio',
        Typ: 'BB',
        Marine: 'Regia Marina',
        Datierung: null,
        Beschreibung: 'RM Andrea Doria, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 170,
        Schiff: 'Trieste',
        Klasse: 'Trento',
        Typ: 'CA',
        Marine: 'Regia Marina',
        Datierung: null,
        Beschreibung: 'RM Trieste, Crew, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Ediz. Cav. Falzone - Corso Cavour, 31 - Spezia.',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 171,
        Schiff: 'Conte di Cavour',
        Klasse: 'Conte-di-Cavour',
        Typ: 'BB',
        Marine: 'Regia Marina',
        Datierung: null,
        Beschreibung: 'RM Cone di Cavour mit Giulio Cesare, nach Modernisierung, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Vera fotografia, Alterocca Terni',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 172,
        Schiff: 'Trieste',
        Klasse: 'Trento',
        Typ: 'CA',
        Marine: 'Regia Marina',
        Datierung: null,
        Beschreibung: 'RM Trieste, Illustration, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Insituto Editoriale Avio-Navale - Milano',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 173,
        Schiff: 'Trento',
        Klasse: 'Trento',
        Typ: 'CA',
        Marine: 'Regia Marina',
        Datierung: null,
        Beschreibung: 'RM Trento, Illustration, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Luigi Alfieri e C. ed., Milano-Roma',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 174,
        Schiff: 'Regina Margherita',
        Klasse: 'Regina Margherita',
        Typ: 'BB',
        Marine: 'Regia Marina',
        Datierung: null,
        Beschreibung: 'RM Regina Margherita, Illustration, Steuerbord',
        Fotograph: 'M. Melansch/ Franco Suipi(?)',
        Verlagsbezeichnung: 'Pubblicazione autorizzata dalla "Lega Navale Italiana"; F. Sottani Editore - Roma',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 175,
        Schiff: 'Dante Alighieri',
        Klasse: 'Dante Alighieri',
        Typ: 'BB',
        Marine: 'Regia Marina',
        Datierung: null,
        Beschreibung: 'RM Dante Alighieri, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N1'
    },
    {
        Postkarte: 176,
        Schiff: 'Leonardo da Vinci',
        Klasse: 'Conte-di-Cavour',
        Typ: 'BB',
        Marine: 'Regia Marina',
        Datierung: null,
        Beschreibung: 'RM Leonardo da Vinci, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'IPA C T Fotocolor',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 177,
        Schiff: 'Regina Elena',
        Klasse: 'Regina Elena',
        Typ: 'BB',
        Marine: 'Regia Marina',
        Datierung: null,
        Beschreibung: 'RM Regina Elena, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 178,
        Schiff: 'Sicilia',
        Klasse: 'Re Umberto',
        Typ: 'BB',
        Marine: 'Regia Marina',
        Datierung: 1903,
        Beschreibung: 'RM Sicilia, 18 Jänner 1903, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Serie Mignon - Proprietà riservata della Cartoleria Milano, Spezia.',
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 179,
        Schiff: 'Démocratie',
        Klasse: 'Liberté',
        Typ: 'BB',
        Marine: 'Marine nationale',
        Datierung: null,
        Beschreibung: 'MN Démocratie, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'E..D',
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 180,
        Schiff: 'Boulonnais',
        Klasse: "L'Adroit",
        Typ: 'DD',
        Marine: 'Marine nationale',
        Datierung: null,
        Beschreibung: 'MN Boulonnais, Crew, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Edition Lèon Barra - Papeterie en gros - TOULON',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 181,
        Schiff: 'Rèpublique',
        Klasse: 'République',
        Typ: 'BB',
        Marine: 'Marine nationale',
        Datierung: 1912,
        Beschreibung: 'MN Républicque, 16. Juni 1912, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 1,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 182,
        Schiff: 'Justice',
        Klasse: 'Liberté',
        Typ: 'BB',
        Marine: 'Marine nationale',
        Datierung: 1914,
        Beschreibung: 'MN Justice, 8. August 1914, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: null,
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 183,
        Schiff: 'Dunkerque',
        Klasse: 'Dunkerque',
        Typ: 'BB',
        Marine: 'Marine nationale',
        Datierung: null,
        Beschreibung: 'MN Dunkerque, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Héliogravure Lesguyer, 16, r. Remparts-dÀinay, Lyon',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 184,
        Schiff: 'Sardegna',
        Klasse: 'Re Umberto',
        Typ: 'BB',
        Marine: 'Regia Marina',
        Datierung: null,
        Beschreibung: 'RM Sardegna, Crew, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Alterocca - Terni',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 185,
        Schiff: 'Garibaldi',
        Klasse: 'Giuseppe Garibaldi',
        Typ: 'C',
        Marine: 'Regia Marina',
        Datierung: null,
        Beschreibung: 'RN Garibaldi, Crew, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Alterocca - Terni',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 186,
        Schiff: 'Glorious',
        Klasse: 'Courageous',
        Typ: 'CB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Glorious, vor Umbau, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Tom Molland Ltd, 102 Cornwall Street Plymouth',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 187,
        Schiff: 'Hawkins',
        Klasse: 'Hawkins',
        Typ: 'CA',
        Marine: 'Royal Navy',
        Datierung: 1935,
        Beschreibung: 'HMS Hawkins, Juli 1935, Portsmouth, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers, Albert Road, Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 188,
        Schiff: 'Dauntless',
        Klasse: 'D-Class',
        Typ: 'CL',
        Marine: 'Royal Navy',
        Datierung: 1932,
        Beschreibung: 'HMS Dauntless, Oktober 1932, Portsmouth, Crew, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers, Albert Road, Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 189,
        Schiff: 'Curlew',
        Klasse: 'C-Class-Cruiser',
        Typ: 'CL',
        Marine: 'Royal Navy',
        Datierung: 1937,
        Beschreibung: 'HMS Curlew, Mai 1937, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers, Albert Road, Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 190,
        Schiff: 'Carlisle',
        Klasse: 'C-Class-Cruiser',
        Typ: 'CL',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Carlisle(?), Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Tom Molland Ltd, 102 Cornwall Street Plymouth',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 191,
        Schiff: 'Oklahoma',
        Klasse: 'Nevada',
        Typ: 'BB',
        Marine: 'United States Navy',
        Datierung: 1936,
        Beschreibung: 'USS Oklahoma, Juni 1936, Portsmouth, Crew, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers, Albert Road, Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 192,
        Schiff: 'Oklahoma',
        Klasse: 'Nevada',
        Typ: 'BB',
        Marine: 'United States Navy',
        Datierung: 1936,
        Beschreibung: 'USS Oklahoma, Juni 1936, Portsmouth, Crew, Heck, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers, Albert Road, Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 193,
        Schiff: 'Royal Oak',
        Klasse: 'Revenge',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Royal Oak, September 1936, Portsmouth, Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers, Albert Road, Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 194,
        Schiff: 'Ramillies',
        Klasse: 'Revenge',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Ramillies,  Juli 1939, Portsmouth, Crew, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers, Albert Road, Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 195,
        Schiff: 'Royal Sovereign',
        Klasse: 'Revenge',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: null,
        Beschreibung: 'HMS Royal Sovereign, August 1935, Portsmouth, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers, Albert Road, Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 196,
        Schiff: 'Graf Zeppelin',
        Klasse: 'Graf Zeppelin',
        Typ: 'CV',
        Marine: 'Kriegsmarine',
        Datierung: 1940,
        Beschreibung: 'KM Graf Zeppelin, Steuerbord',
        Fotograph: null,
        Verlagsbezeichnung: "Foto Drüppel, 294 W'Haven, KM2077",
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 197,
        Schiff: 'Gustav V',
        Klasse: 'Sverige',
        Typ: 'BB',
        Marine: 'Schwedische Marine',
        Datierung: 1946,
        Beschreibung: 'HSwMS Gustav V, Mai 1937, Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Tom Molland Ltd, 102 Cornwall Street Plymouth',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 198,
        Schiff: 'Howe',
        Klasse: 'King-George-V (1940)',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1947,
        Beschreibung: 'HMS Howe, Mai 1947, Portsmouth, Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers, Albert Road, Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 199,
        Schiff: 'Drottning Victoria',
        Klasse: 'Sverige',
        Typ: 'BB',
        Marine: 'Schwedische Marine',
        Datierung: 1937,
        Beschreibung: 'HSwMS Drottning Victoria, Mai 1937, Spithead, Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers, Albert Road, Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 200,
        Schiff: 'Kléber',
        Klasse: 'Zerstörer 1934',
        Typ: 'DD',
        Marine: 'Marine nationale',
        Datierung: 1953,
        Beschreibung: 'MN Kléber, vormals KM Z6 Theodor Riedel, Mai 1953, Portsmouth',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers, Albert Road, Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 202,
        Schiff: 'Vanguard',
        Klasse: 'Vanguard',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1946,
        Beschreibung: 'HMS Vanguard, Dezember 1946, Portsmouth, Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers, Albert Road, Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 203,
        Schiff: 'Vanguard',
        Klasse: 'Vanguard',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1953,
        Beschreibung: 'HMS Vanguard, Mai 1953, Portsmouth, Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers, Albert Road, Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    },
    {
        Postkarte: 204,
        Schiff: 'Duke of York',
        Klasse: 'King-George-V (1940)',
        Typ: 'BB',
        Marine: 'Royal Navy',
        Datierung: 1947,
        Beschreibung: 'HMS Duke of York, Jänner 1947, Portsmouth, Crew, Backbord',
        Fotograph: null,
        Verlagsbezeichnung: 'Wright & Logan Photographers, Albert Road, Southsea',
        Gelaufen: 0,
        Format: '10x15',
        'Schachtel': 'N2'
    }

];

$(document).ready( function () {
    $('#card_list').DataTable({
        "data": boote,
        "columns": [
            {"data": "boote.Schiff"},
            {"data": "boote.Klasse"},
            {"data": "boote.Beschreibung"},
            {"data": "boote.Datierung"}
        ]
    });
})





// function onClick(data) {
//     //head
//     let div = document.createElement("div");
//     div.setAttribute("class", "collapse");
//     div.setAttribute("id", "generated")
//     let table = document.createElement("table");
//     table.setAttribute("class", "table align-middle table-hover")
//     let fields = Object.keys(data[0]);
//     let thead = document.createElement("thead");
//     let head_row = document.createElement("tr");
//     fields.forEach(function(field) {
//         if (field !== "Postkarte" || field !== 'Schachtel' || field !== "Typ" || field !== "Marine"
//         || field !== "Fotograph" || field !== "Verlgasbezeichnung" || field !== "Gelaufen"
//             || field !== "Format" || field !== "Klasse")  {
//             let head_cell = document.createElement("th");
//             head_cell.textContent = field;
//             head_cell.setAttribute("class", "loc-related-heading");
//             head_cell.setAttribute("scope", "col");
//             head_row.appendChild(head_cell);
//
//         }
//     });
//     thead.appendChild((head_row));
//     //body
//     data.forEach(function(obj) {
//         let row = document.createElement("tr");
//         fields.forEach(function(field) {
//             if (field !== "Postkarte" || field !== 'Schachtel' || field !== "Typ" || field !== "Marine"
//                 || field !== "Fotograph" || field !== "Verlgasbezeichnung" || field !== "Gelaufen"
//                 || field !== "Format" || field !== "Klasse") {
//                 let cell = ducment.createElement("td");
//                 if (field === "Schiff") {
//                     row.setAttribute("class", "entry-ship")
//                 };
//                 if (field ==="Beschreibung") {
//                     row.setAttribute("class", "entry-desc")
//                 };
//                 if (field ==="Datierung") {
//                     row.setAttribute("class", "entry-timespan")
//                 };
//
//             }
//         });
//         table.appendChild(row);
//     })
//     return div
// }
// document.querySelector(#generate).appendChild(onClick(boote));
